# Generated by Django 5.1.6 on 2025-03-22 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_chatmessage_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='profile_pic',
        ),
    ]
