# Generated by Django 5.1.6 on 2025-03-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_chatmessage_file_chatmessage_message_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
